Introduce album thumbnail images.
Processed from existing images within the folder (max 1) with sharp and stored with jetpack.

For some reason, I never could sharp to write files. It would always fail with
```
Error: vips__file_open_write: unable to open file "static\generated\thumbnails\f7c02833-9b60-48aa-a413-d82380e7a6a6.jpg" for writing
windows error: Die Adresse des Speichersteuerblocks ist unzulässig.
```

One drawback of the current implementation is that the category SVGs don't look so nice at 200x200 pixels.